modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="eldencraft"
version="${file.jarVersion}"
displayName="eldencraft"
logoFile="examplemod.png"
credits='''
    Codebase writer, Item/Block data management, Textures: Diglis
    (Future) Coder, Event handling: Thomas
'''
authors="Love, Cheese and small house plants"
description='''

'''
[[dependencies.eldencraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.eldencraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
